language: python
python: '2.7'
sudo: required
env:
  #matrix:
  - OS_VERSION=5 OS_TYPE=centos
  - OS_VERSION=6 OS_TYPE=centos

branches:
  only:
  - master
#  - stable

services:
  - docker

before_install:
  - docker pull centos:5
  - docker pull centos:6
  - docker pull centos:7

script:
 # Run tests on CentOs
 - docker run --rm=true -v `pwd`:/ansible-pycharm:rw $OS_TYPE:$OS_VERSION /bin/bash -c "/fragroute/tests/test-on-rpm.sh"


#notifications:
#  email: false
#  hipchat:
#    rooms:

